server:
  port: 18010

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:18761/eureka}
  instance:
    preferIpAddress: true
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      authentication-database: bank-products-db
      username: admin
      password: admin
      database: bank-products-db