server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: bank-transactions-db
      username: admin
      password: admin
      database: bank-transactions-db
