server:
  port: 28030
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:28761/eureka}
  instance:
    preferIpAddress: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27019
      authentication-database: bank-customers-db
      username: admin
      password: admin
      database: bank-customers-db